# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-11 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_unit', '0012_businessunit_unit_code'),
        ('projects', '0002_auto_20190222_1824'),
        ('AMC_Report', '0002_auto_20190611_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmcHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amc_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=200, verbose_name='AMC_description')),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=10, null=True, verbose_name='AMC_frequency period(in Months)')),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('file_document', models.FileField(blank=True, null=True, upload_to='AmcHistory')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('amc_renewal_date', models.DateField(blank=True, null=True)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amc_client_names', to='business_unit.BusinessUnit', verbose_name='AMC_Clients')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amc_project_names', to='projects.Project', verbose_name='AMC_Project Names')),
            ],
            options={
                'db_table': 'AMC_History',
                'verbose_name_plural': 'AMC Report',
            },
        ),
        migrations.CreateModel(
            name='ReportAMC1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('1', '1 Month'), ('2', '2 Months'), ('3', '3 Months'), ('4', '4 Months'), ('5', '5 Months'), ('6', '6 Months'), ('7', '7 Months'), ('8', '8 Months'), ('9', '9 Months'), ('10', '10 Months'), ('11', '11 Months'), ('12', '12 Months'), ('13', '13 Month'), ('14', '14 Months'), ('15', '15 Months'), ('16', '16 Months'), ('17', '17 Months'), ('18', '18 Months'), ('19', '19 Months'), ('20', '20 Months'), ('21', '21 Months'), ('22', '22 Months'), ('23', '23 Months'), ('24', '24 Months'), ('25', '25 Month'), ('26', '6 Months'), ('27', '27 Months'), ('28', '28 Months'), ('29', '29 Months'), ('30', '30 Months'), ('31', '31 Months'), ('32', '32 Months'), ('33', '33 Months'), ('34', '34 Months'), ('35', '35 Months'), ('36', '36 Months')], max_length=10, null=True, verbose_name='Frequency Period(in Months)')),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='Amc_documents/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('amc_created_date', models.DateField(blank=True, null=True)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClientName', to='business_unit.BusinessUnit', verbose_name='Client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectName', to='projects.Project', verbose_name='Project Name')),
            ],
            options={
                'db_table': 'AMC',
                'verbose_name_plural': 'AMC Report',
            },
        ),
    ]
