# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-18 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='business_unit',
        ),
    ]
