# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-18 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0006_businessunit_unit_code'),
        ('users', '0002_remove_userprofile_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_unit',
            field=models.ManyToManyField(to='business_unit.BusinessUnit', verbose_name='business unit'),
        ),
    ]
