# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-19 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0006_businessunit_unit_code'),
        ('users', '0003_userprofile_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_unit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_userprofile_business_unit', to='business_unit.BusinessUnit', verbose_name='Business unit'),
            preserve_default=False,
        ),
    ]
