# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-31 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190131_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='business_unit_code',
        ),
    ]
