# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0010_delete_employeetype'),
        ('users', '0010_remove_userprofile_business_unit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_unit_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_userprofile_business_unit_code', to='business_unit.BusinessUnit', verbose_name='BusinessUnitCode'),
            preserve_default=False,
        ),
    ]
