# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement_new',
            name='approved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement_new',
            name='processed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
