# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_reimbursement', '0003_reimbursement_new_reimbursement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement_new',
            name='reimbursement_date',
        ),
    ]
