# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_reimbursement', '0004_remove_reimbursement_new_reimbursement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement_new',
            name='reimbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
