# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-11 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now=True, null=True)),
                ('leave_from', models.DateField(blank=True, null=True)),
                ('leave_to', models.DateField(blank=True, null=True)),
                ('no_of_days', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('leave_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('approval_status', models.CharField(default='Not Yet Approved', max_length=200)),
                ('reject_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('lop', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('approved_by', models.ForeignKey(db_column='approved_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='approved_by')),
                ('empid', models.ForeignKey(db_column='empid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_empid', to=settings.AUTH_USER_MODEL, verbose_name='empid')),
            ],
            options={
                'db_table': 'leave_requests',
                'verbose_name_plural': 'Leave Request ',
            },
        ),
        migrations.CreateModel(
            name='ShortLeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('leave_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('no_of_hours', models.IntegerField(default=1)),
                ('approval_status', models.CharField(max_length=200)),
                ('reject_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('approved_by', models.ForeignKey(db_column='approved_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_shortleaverequest_manager', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('empid', models.ForeignKey(db_column='empid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_shortleaverequest_employee', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'db_table': 'shortleave_requests',
                'verbose_name_plural': 'Short Leave Request ',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=200)),
                ('cur_year', models.IntegerField()),
                ('leave_id', models.IntegerField()),
                ('total_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('balance_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'leave_statuses',
                'verbose_name_plural': 'Leave Status',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=200)),
                ('no_of_days', models.IntegerField()),
                ('current_year', models.IntegerField()),
                ('leave_status', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'leave_types',
                'verbose_name_plural': 'Leave Type',
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_nature',
            field=models.ForeignKey(db_column='leave_nature', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leaverequest_leave_nature', to='leave.Type', verbose_name='leave_nature'),
        ),
    ]
