# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortleaverequest',
            name='approval_status',
            field=models.CharField(default='Not Yet Approved', max_length=200),
        ),
        migrations.AlterField(
            model_name='shortleaverequest',
            name='no_of_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shortleaverequest',
            name='request_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
