# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20181019_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
