# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-19 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20181019_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
