# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-22 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaverequest_is_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_pending',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_rejected',
        ),
    ]
