# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-22 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20181022_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='approval_status',
        ),
    ]
