# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-22 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_remove_leaverequest_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approval_status',
            field=models.CharField(default='Not Yet Approved', max_length=200),
        ),
    ]
