# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leaverequest_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortleaverequest',
            name='request_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
