# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20181024_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortleaverequest',
            name='approval_status',
            field=models.CharField(default='Not Yet Approved', max_length=200),
        ),
    ]
