# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-26 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_auto_20181026_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortleaverequest',
            name='no_of_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True),
        ),
    ]
