# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_leavecredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecredit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavecredit',
            name='leave_id',
            field=models.IntegerField(db_column='leave_id'),
        ),
    ]
