# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-05 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_auto_20181105_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecredit',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='leavecredit',
            name='leave_id',
        ),
        migrations.DeleteModel(
            name='LeaveCredit',
        ),
    ]
