# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-05 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0017_auto_20181105_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCredit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_days', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('credit_date', models.DateField(auto_now=True, null=True)),
                ('cur_year', models.IntegerField()),
                ('empid', models.ForeignKey(db_column='empid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leavecredit_users', to=settings.AUTH_USER_MODEL, verbose_name='users')),
                ('leave_id', models.ForeignKey(db_column='leave_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_leavecredit_leave_type', to='leave.Type', verbose_name='leave_type')),
            ],
            options={
                'db_table': 'leave_credit',
                'verbose_name_plural': 'Leave Credit ',
            },
        ),
    ]
