# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0018_leavecredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='approval_status',
            field=models.CharField(max_length=200),
        ),
    ]
