# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-27 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_auto_20181224_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecredit',
            name='previous_leave_balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
