# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-04 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_leavecredit_previous_leave_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecredit',
            name='previous_leave_balance',
        ),
    ]
