# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0021_remove_leavecredit_previous_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='approval_status',
            field=models.CharField(default='Not Yet Approved', max_length=200),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_reason',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='shortleaverequest',
            name='leave_reason',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
