# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0022_auto_20190122_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortleaverequest',
            name='leave_reason',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
