# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0023_auto_20190122_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortleaverequest',
            name='leave_reason',
        ),
        migrations.RemoveField(
            model_name='shortleaverequest',
            name='reject_reason',
        ),
    ]
