# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-11 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190122_1549'),
        ('leave', '0025_auto_20190122_1408'),
    ]

    operations = [
    ]
