# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-12 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0027_lateattendance'),
        ('leave', '0005_lateattendance'),
    ]

    operations = [
    ]
