# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-12 17:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0028_merge_20190612_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortleaverequest',
            name='no_of_hours',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
