# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-12 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0029_auto_20190612_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortleaverequest',
            name='no_of_hours',
        ),
    ]
