# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-12 17:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0030_remove_shortleaverequest_no_of_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortleaverequest',
            name='no_of_hours',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
