# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-20 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0033_auto_20190620_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_of_year', models.CharField(max_length=10)),
                ('late_attendance_count', models.IntegerField()),
                ('empid', models.ForeignKey(db_column='empid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_lateattendance_employeeID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'late_Attendance',
                'verbose_name_plural': 'late_attendances',
            },
        ),
    ]
