# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-23 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0008_businessunit_unit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_type', models.CharField(max_length=40)),
                ('default_code', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['employee_type'],
                'verbose_name': 'Employee Type',
                'verbose_name_plural': 'Employee Types',
            },
        ),
    ]
